code --install-extension adpyke.codesnap
code --install-extension alefragnani.project-manager
code --install-extension amiralizadeh9480.laravel-extra-intellisense
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension bradlc.vscode-tailwindcss
code --install-extension brapifra.phpserver
code --install-extension cjhowe7.laravel-blade
code --install-extension codingyu.laravel-goto-view
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension evan-buss.font-switcher
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension GitHub.vscode-pull-request-github
code --install-extension glitchbl.laravel-create-view
code --install-extension hbenl.vscode-test-explorer
code --install-extension IHunte.laravel-blade-wrapper
code --install-extension ii3i.min
code --install-extension junstyle.php-cs-fixer
code --install-extension liamhammett.inline-parameters
code --install-extension m1guelpf.better-pest
code --install-extension marabesi.php-import-checker
code --install-extension MehediDracula.php-namespace-resolver
code --install-extension miguelsolorio.fluent-icons
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode.test-adapter-converter
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension naoray.laravel-goto-components
code --install-extension neilbrayfield.php-docblocker
code --install-extension oderwat.indent-rainbow
code --install-extension onecentlin.laravel-blade
code --install-extension onecentlin.laravel5-snippets
code --install-extension patbenatar.advanced-new-file
code --install-extension rangav.vscode-thunder-client
code --install-extension redhat.vscode-yaml
code --install-extension rifi2k.format-html-in-php
code --install-extension ryannaddy.laravel-artisan
code --install-extension shufo.vscode-blade-formatter
code --install-extension sleistner.vscode-fileutils
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension Tyriar.lorem-ipsum
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wraith13.file-path-bar